services:
  postgres:
    container_name: postgres
    image: postgres:15
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    
volumes:
  postgres_data: