---
- name: Configure Kubernetes Cluster
  hosts: k8s_nodes
  become: true
  tasks:
    - name: Install required packages
      apt:
        name: 
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - snapd
        state: present
        update_cache: yes

    - name: Install kubeadm, kubelet, and kubectl
      snap:
        name: 
          - kubeadm
          - kubelet
          - kubectl
        state: present
        classic: true

    - name: Disable swap
      shell: |
        swapoff -a
        sed -i '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab

    - name: Enable and start kubelet service
      service:
        name: kubelet
        enabled: yes
        state: started