---
- name: Configure Kubernetes Cluster
  hosts: k8s_worker
  become: true
  tasks:
    - name: Install required packages
      apt:
        name: 
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - snapd
        state: present
        update_cache: yes

    - name: Install kubeadm and kubelet
      snap:
        name: 
          - kubeadm
          - kubelet
        state: present
        classic: true

    - name: Disable swap
      shell: |
        swapoff -a
        sed -i '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab
