---
- name: Configure Kubernetes Cluster
  hosts: k8s_master
  become: true
  tasks:
    - name: Install required packages
      apt:
        name: 
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - snapd
          - containerd
        state: present
        update_cache: yes

    - name: Add Kubernetes GPG key
      shell: |
        mkdir -p -m 755 /etc/apt/keyrings
        curl -fsSL https://pkgs.k8s.io/core:/stable:/v{{ k8s_version.split('.') | take(2) | join('.') }}/doc/apt-key.gpg | gpg --dearmor | sudo tee /etc/apt/keyrings/kubernetes-apt-keyring.gpg
        
    - name: Install Kubernetes APT Repository
      shell: |
        echo 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v{{ k8s_version.split('.')[0] }}.{{ k8s_version.split('.')[1] }}/deb/ /' | sudo tee /etc/apt/sources.list.d/kubernetes.list

    - name: Install kubeadm, kubelet, and kubectl
      shell: |
        apt-get update
        apt-get install -y kubelet kubeadm kubectl
        apt-mark hold kubelet kubeadm kubectl

    - name: Install cri-tools
      shell: |
        curl -LOsS https://github.com/kubernetes-sigs/cri-tools/releases/download/v{{ k8s_version }}/crictl-v{{ k8s_version }}-linux-amd64.tar.gz
        tar zxvf crictl-v{{ k8s_version }}-linux-amd64.tar.gz -C /usr/local/bin
        rm crictl-v{{ k8s_version }}-linux-amd64.tar.gz
        crictl --version

    - name: Config cri-tools
      shell: |
        tee /etc/crictl.yaml <<EOF
        runtime-endpoint: unix:///var/run/containerd/containerd.sock
        EOF
        crictl info

    - name: Disable swap
      shell: |
        swapoff -a
        sed -i '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab
        
    - name: Enable and start kubelet service
      service:
        name: kubelet
        enabled: yes
        state: started

    - name: Enable port forwarding
      shell: |
        sysctl net.ipv4.ip_forward=1
        
    - name: Initialize Kubernetes Control Plane
      shell: |
        kubeadm init --pod-network-cidr=192.168.0.0/16 --control-plane-endpoint={{ load_balancer_ip }}
        mkdir -p $HOME/.kube
        cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
        chown $(id -u):$(id -g) $HOME/.kube/config

    - name: Install Calico Network Plugin
      shell: |
        kubectl apply -f https://docs.projectcalico.org/manifests/calico.yaml
    
    - name: Print Join Command
      shell: |
        kubeadm token create --print-join-command > /tmp/join-command.sh
        chmod +x /tmp/join-command.sh
        cat /tmp/join-command.sh
