---
- name: Configure Nginx Load Balancer
  hosts: nginx
  become: true
  tasks:
    - name: Install Nginx
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Copy Nginx configuration file
      copy:
        src: /home/runner/work/infra/infra/nginx/nginx.conf
        dest: /etc/nginx/nginx.conf

    - name: Restart Nginx
      service:
        name: nginx
        state: restarted