name: Deploy Kafka (Lightsail)

on:
  push:
    branches:
      - main

jobs:
  terraform-apply: 
    name: Set up Lightsail Instance
    runs-on: ubuntu-latest
    outputs:
        INSTANCE_IP: ${{ steps.get_instance_ip.outputs.INSTANCE_IP }}
    permissions:
        id-token: write
        contents: read
    env:
        TF_PATH: ./terraform/environments/dev
        LIGHTSAIL_KEY_PAIR_NAME: github_action_${{ github.run_id }}
    steps: 
        - name: Checkout
          uses: actions/checkout@v4

        - name: Setup Terraform
          uses: hashicorp/setup-terraform@v2
          with:
              terraform_version: 1.5.0
              terraform_wrapper: false
        
        - name: Setup AWS Credentials
          uses: aws-actions/configure-aws-credentials@v3
          with:
              role-to-assume: arn:aws:iam::730335465394:role/github_actions_role
              aws-region: ap-southeast-1

        - name: Generate Temporary SSH Key with PEM format
          run: |
            mkdir -p ./tmp
            ssh-keygen -t rsa -b 2048 -m PEM -f ./tmp/temp_key -N ""
            PUBLIC_KEY=$(cat ./tmp/temp_key.pub)
            echo "PUBLIC_KEY=$PUBLIC_KEY" >> "$GITHUB_ENV" 
    
        - name: Terraform Initialize
          run: terraform -chdir=${TF_PATH} init 

        - name: Terraform Apply
          if: github.ref == 'refs/heads/main' && github.event_name == 'push'
          run: terraform -chdir=${TF_PATH} apply -auto-approve -var="key_pair_name=${LIGHTSAIL_KEY_PAIR_NAME}" -var="public_key=${PUBLIC_KEY}"
        
        - name: Get Instance IP
          id: get_instance_ip
          run: |
            INSTANCE_IP=$(terraform -chdir=${TF_PATH} output -raw instance_ip)
            echo "INSTANCE_IP=$INSTANCE_IP" >> "$GITHUB_OUTPUT"
        
        - name: Create Keypair artifact
          uses: actions/upload-artifact@v3
          with:
              name: lightsail_keypair
              path: ./tmp/temp_key
        
  helm-deploy:
    name: Helm Deploy
    runs-on: ubuntu-latest
    needs: terraform-apply
    env:
        INSTANCE_IP: ${{ needs.terraform-apply.outputs.INSTANCE_IP }}
    permissions:
        id-token: write
        contents: read
    steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Setup AWS Credentials
          uses: aws-actions/configure-aws-credentials@v3
          with:
              role-to-assume: arn:aws:iam::730335465394:role/github_actions_role
              aws-region: ap-southeast-1

        - name: Download Keypair artifact
          uses: actions/download-artifact@v3
          with:
              name: lightsail_keypair
              path: ./tmp
        - name: Tree Directory
          run: tree

        - name: Protect Keypair
          run: chmod 600 ./tmp/temp_key

        - name: Get Lightsail Instance
          run: aws lightsail get-instance --instance-name "k3s-lightsail"

        - name: Install Dependencies
          run: |
            ssh -i ./tmp/temp_key -o StrictHostKeyChecking=no ubuntu@$INSTANCE_IP 'bash -s' < ./scripts/install-dependencies.sh

        - name: Helm Setup Kafka
          run: |
            ssh -i ./tmp/temp_key -o StrictHostKeyChecking=no ubuntu@$INSTANCE_IP 'bash -s' < ./scripts/deploy-kafka.sh
