name: Deploy to Development Environment
on:
    push:
        branches:
            - dev

jobs:
    provision:
        name: Setup Instances 
        runs-on: ubuntu-latest
        permissions:
            id-token: write
            contents: read
        env: 
            TF_PATH: ./terraform/environments/dev
            AWS_INSTANCE_SSH_KEYPAIR_NAME: github_action_ssh
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            
            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v2
              with:
                  terraform_version: 1.5.0
                  terraform_wrapper: false

            - name: Setup AWS Credentials
              uses: aws-actions/configure-aws-credentials@v3
              with:
                role-to-assume: arn:aws:iam::730335465394:role/github_actions_role
                aws-region: ap-southeast-1

            - name: Terraform Apply 
              run: |
                terraform -chdir=$TF_PATH init
                terraform -chdir=$TF_PATH apply -auto-approve -var="key_pair_name=${AWS_INSTANCE_SSH_KEYPAIR_NAME}"
              
            - name: Write IPs to Inventory
              run: |
                chmod +x ./scripts/generate_inventory.sh
                ./scripts/generate_inventory.sh $TF_PATH
              shell: bash

            - name: Check Inventory
              run: |
                cat ./ansible/inventory.ini
            
            - name: Create inventory artifact
              uses: actions/upload-artifact@v2
              with:
                name: inventory
                path: ./ansible/inventory.ini

    configure:
        name: Configure Instances
        runs-on: ubuntu-latest
        needs: provision
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Ansible
              run: |
                sudo apt update
                sudo apt install -y ansible

            - name: Write SSH Key
              run: |
                mkdir -p ~/.ssh
                echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
                chmod 600 ~/.ssh/id_rsa
            
            - name: Download Inventory
              uses: actions/download-artifact@v2
              with:
                name: inventory

            - name: Ping Ansible Hosts
              run: |
                ansible -i ./ansible/inventory.ini all -m ping
            
            - name: Configure Nginx Load Balancer
              run: |
                ansible-playbook -i ./ansible/inventory.ini -l nginx ./ansible/playbooks/nginx.yml

            - name: Configure Kubernetes Cluster
              run: |
                ansible-playbook -i ./ansible/inventory.ini -l k8s_nodes ./ansible/playbooks/k8s.yml
